# -*- coding: utf-8 -*-
"""m2_s3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgNwwTBAas3460n44G8YAOryaAtqBiww
"""

!pip install langchain langgraph pandas langchain-openrouter fastmcp

import os
# ====== PUT YOUR KEYS HERE ======
os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_KEY"
os.environ["OPENROUTER_API_KEY"] = "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"
os.environ["GOOGLE_API_KEY"] = "YOUR_GEMINI_KEY"

from langchain.chat_models import init_chat_model
def get_llm(provider):
  if provider=="openrouter":
    llm = init_chat_model(
        "openai/gpt-4o-mini",
        model_provider="openrouter"
    )
  elif provider=="chatgpt":
    llm = init_chat_model("gpt-4o-mini", model_provider="openai")
  elif provider=="gemini":
    llm = init_chat_model(
      "gemini-1.5-pro",
      model_provider="google_genai"
    )
  else:
    raise Exception("Invalid provider")
  return llm
# --- OPTION 1: OpenAI ---
model="openrouter" #chatgpt, gemini
llm = get_llm(provider=model)

import pandas as pd
from langchain.tools import tool
#from langgraph.prebuilt import create_react_agent
from langchain.agents import create_agent

@tool
def clean_csv(file_path: str) -> str:
    """
    Load a CSV and perform basic cleaning:
    - drop duplicates
    - fill NA with median (numeric)
    - return summary
    """
    df = pd.read_csv(file_path)

    df = df.drop_duplicates()

    for col in df.select_dtypes(include="number").columns:
        df[col] = df[col].fillna(df[col].median())

    return f"Cleaned DataFrame shape: {df.shape}\nColumns: {list(df.columns)}"


tools = [clean_csv]

agent = create_agent(
    model=llm,
    tools=tools,
)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# #rm -r gdpymes/
# git clone https://github.com/bsaldivaremc2/gdpymes.git

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# unzip /content/gdpymes/datasets/wine+quality.zip

csv_path = "/content/winequality-red.csv"

result = agent.invoke({
    "messages": [{"role": "user", "content": "Clean the CSV at "+csv_path}]
})

result

import importlib
import sys

SUPPORT_DIRECTORY = "gdpymes/march2026/"
sys.path.append(SUPPORT_DIRECTORY)